# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tcpServer.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(772, 552)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.onlinePeopleLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.onlinePeopleLabel.setFont(font)
        self.onlinePeopleLabel.setObjectName("onlinePeopleLabel")
        self.horizontalLayout.addWidget(self.onlinePeopleLabel)
        self.onlineNumLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.onlineNumLabel.setFont(font)
        self.onlineNumLabel.setObjectName("onlineNumLabel")
        self.horizontalLayout.addWidget(self.onlineNumLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.userListWidget = QtWidgets.QListWidget(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.userListWidget.setFont(font)
        self.userListWidget.setObjectName("userListWidget")
        self.verticalLayout.addWidget(self.userListWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.contentListWidget = QtWidgets.QListWidget(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.contentListWidget.setFont(font)
        self.contentListWidget.setObjectName("contentListWidget")
        self.horizontalLayout_2.addWidget(self.contentListWidget)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.portLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.portLabel.setFont(font)
        self.portLabel.setObjectName("portLabel")
        self.gridLayout_2.addWidget(self.portLabel, 1, 0, 1, 1)
        self.serverIPLineEdit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.serverIPLineEdit.setFont(font)
        self.serverIPLineEdit.setObjectName("serverIPLineEdit")
        self.gridLayout_2.addWidget(self.serverIPLineEdit, 0, 1, 1, 1)
        self.serverIPLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.serverIPLabel.setFont(font)
        self.serverIPLabel.setObjectName("serverIPLabel")
        self.gridLayout_2.addWidget(self.serverIPLabel, 0, 0, 1, 1)
        self.portLineEdit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.portLineEdit.setFont(font)
        self.portLineEdit.setObjectName("portLineEdit")
        self.gridLayout_2.addWidget(self.portLineEdit, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.openBtn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.openBtn.setFont(font)
        self.openBtn.setObjectName("openBtn")
        self.verticalLayout_2.addWidget(self.openBtn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TCP Server"))
        self.onlinePeopleLabel.setText(_translate("Form", "Online People:"))
        self.onlineNumLabel.setText(_translate("Form", "0"))
        self.portLabel.setText(_translate("Form", "Port："))
        self.serverIPLabel.setText(_translate("Form", "Server IP："))
        self.openBtn.setText(_translate("Form", "Open Chat Room"))

