# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Controller.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(826, 593)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btClose = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btClose.setFont(font)
        self.btClose.setObjectName("btClose")
        self.horizontalLayout_5.addWidget(self.btClose)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spRefFre = QtWidgets.QDoubleSpinBox(Form)
        self.spRefFre.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spRefFre.setFont(font)
        self.spRefFre.setWrapping(False)
        self.spRefFre.setDecimals(1)
        self.spRefFre.setSingleStep(0.5)
        self.spRefFre.setProperty("value", 1.0)
        self.spRefFre.setObjectName("spRefFre")
        self.horizontalLayout_4.addWidget(self.spRefFre)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spSendFre = QtWidgets.QDoubleSpinBox(Form)
        self.spSendFre.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spSendFre.setFont(font)
        self.spSendFre.setWrapping(False)
        self.spSendFre.setDecimals(1)
        self.spSendFre.setSingleStep(0.5)
        self.spSendFre.setProperty("value", 1.0)
        self.spSendFre.setObjectName("spSendFre")
        self.horizontalLayout.addWidget(self.spSendFre)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.btReport = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btReport.setFont(font)
        self.btReport.setObjectName("btReport")
        self.horizontalLayout_5.addWidget(self.btReport)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btCold = QtWidgets.QPushButton(Form)
        self.btCold.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btCold.setFont(font)
        self.btCold.setCheckable(True)
        self.btCold.setChecked(True)
        self.btCold.setAutoExclusive(True)
        self.btCold.setObjectName("btCold")
        self.horizontalLayout_2.addWidget(self.btCold)
        self.btWarm = QtWidgets.QPushButton(Form)
        self.btWarm.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btWarm.setFont(font)
        self.btWarm.setCheckable(True)
        self.btWarm.setAutoExclusive(True)
        self.btWarm.setObjectName("btWarm")
        self.horizontalLayout_2.addWidget(self.btWarm)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(10)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.tbServeQueue = QtWidgets.QTableWidget(self.layoutWidget)
        self.tbServeQueue.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tbServeQueue.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tbServeQueue.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tbServeQueue.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbServeQueue.setObjectName("tbServeQueue")
        self.tbServeQueue.setColumnCount(8)
        self.tbServeQueue.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbServeQueue.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbServeQueue.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbServeQueue.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbServeQueue.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbServeQueue.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbServeQueue.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbServeQueue.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbServeQueue.setHorizontalHeaderItem(7, item)
        self.tbServeQueue.horizontalHeader().setCascadingSectionResizes(False)
        self.tbServeQueue.horizontalHeader().setDefaultSectionSize(100)
        self.tbServeQueue.horizontalHeader().setSortIndicatorShown(False)
        self.tbServeQueue.horizontalHeader().setStretchLastSection(False)
        self.tbServeQueue.verticalHeader().setHighlightSections(True)
        self.tbServeQueue.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.tbServeQueue)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.tbWaitQueue = QtWidgets.QTableWidget(self.layoutWidget1)
        self.tbWaitQueue.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tbWaitQueue.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tbWaitQueue.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tbWaitQueue.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbWaitQueue.setObjectName("tbWaitQueue")
        self.tbWaitQueue.setColumnCount(8)
        self.tbWaitQueue.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbWaitQueue.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbWaitQueue.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbWaitQueue.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbWaitQueue.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbWaitQueue.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbWaitQueue.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbWaitQueue.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbWaitQueue.setHorizontalHeaderItem(7, item)
        self.tbWaitQueue.horizontalHeader().setCascadingSectionResizes(False)
        self.tbWaitQueue.horizontalHeader().setDefaultSectionSize(100)
        self.tbWaitQueue.horizontalHeader().setSortIndicatorShown(False)
        self.tbWaitQueue.horizontalHeader().setStretchLastSection(False)
        self.tbWaitQueue.verticalHeader().setHighlightSections(True)
        self.tbWaitQueue.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_2.addWidget(self.tbWaitQueue)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.tbTempQueue = QtWidgets.QTableWidget(self.layoutWidget2)
        self.tbTempQueue.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tbTempQueue.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tbTempQueue.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tbTempQueue.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbTempQueue.setObjectName("tbTempQueue")
        self.tbTempQueue.setColumnCount(8)
        self.tbTempQueue.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbTempQueue.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbTempQueue.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbTempQueue.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbTempQueue.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbTempQueue.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbTempQueue.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbTempQueue.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbTempQueue.setHorizontalHeaderItem(7, item)
        self.tbTempQueue.horizontalHeader().setCascadingSectionResizes(False)
        self.tbTempQueue.horizontalHeader().setDefaultSectionSize(100)
        self.tbTempQueue.horizontalHeader().setSortIndicatorShown(False)
        self.tbTempQueue.horizontalHeader().setStretchLastSection(False)
        self.tbTempQueue.verticalHeader().setHighlightSections(True)
        self.tbTempQueue.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_3.addWidget(self.tbTempQueue)
        self.verticalLayout_4.addWidget(self.splitter)
        self.splitter.raise_()
        self.spSendFre.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "中控机"))
        self.btClose.setText(_translate("Form", "开机"))
        self.label_2.setText(_translate("Form", "刷新频率"))
        self.label.setText(_translate("Form", "发送频率"))
        self.btReport.setText(_translate("Form", "报表"))
        self.btCold.setText(_translate("Form", "制冷"))
        self.btWarm.setText(_translate("Form", "制热"))
        self.label_4.setText(_translate("Form", "服务队列"))
        self.tbServeQueue.setSortingEnabled(True)
        item = self.tbServeQueue.horizontalHeaderItem(0)
        item.setText(_translate("Form", "房间号"))
        item = self.tbServeQueue.horizontalHeaderItem(1)
        item.setText(_translate("Form", "用户级别"))
        item = self.tbServeQueue.horizontalHeaderItem(2)
        item.setText(_translate("Form", "模式"))
        item = self.tbServeQueue.horizontalHeaderItem(3)
        item.setText(_translate("Form", "室温"))
        item = self.tbServeQueue.horizontalHeaderItem(4)
        item.setText(_translate("Form", "设定温度"))
        item = self.tbServeQueue.horizontalHeaderItem(5)
        item.setText(_translate("Form", "风速"))
        item = self.tbServeQueue.horizontalHeaderItem(6)
        item.setText(_translate("Form", "耗能"))
        item = self.tbServeQueue.horizontalHeaderItem(7)
        item.setText(_translate("Form", "当前计费"))
        self.label_5.setText(_translate("Form", "等待队列"))
        self.tbWaitQueue.setSortingEnabled(True)
        item = self.tbWaitQueue.horizontalHeaderItem(0)
        item.setText(_translate("Form", "房间号"))
        item = self.tbWaitQueue.horizontalHeaderItem(1)
        item.setText(_translate("Form", "用户级别"))
        item = self.tbWaitQueue.horizontalHeaderItem(2)
        item.setText(_translate("Form", "模式"))
        item = self.tbWaitQueue.horizontalHeaderItem(3)
        item.setText(_translate("Form", "室温"))
        item = self.tbWaitQueue.horizontalHeaderItem(4)
        item.setText(_translate("Form", "设定温度"))
        item = self.tbWaitQueue.horizontalHeaderItem(5)
        item.setText(_translate("Form", "风速"))
        item = self.tbWaitQueue.horizontalHeaderItem(6)
        item.setText(_translate("Form", "耗能"))
        item = self.tbWaitQueue.horizontalHeaderItem(7)
        item.setText(_translate("Form", "当前计费"))
        self.label_6.setText(_translate("Form", "回温队列"))
        self.tbTempQueue.setSortingEnabled(True)
        item = self.tbTempQueue.horizontalHeaderItem(0)
        item.setText(_translate("Form", "房间号"))
        item = self.tbTempQueue.horizontalHeaderItem(1)
        item.setText(_translate("Form", "用户级别"))
        item = self.tbTempQueue.horizontalHeaderItem(2)
        item.setText(_translate("Form", "模式"))
        item = self.tbTempQueue.horizontalHeaderItem(3)
        item.setText(_translate("Form", "室温"))
        item = self.tbTempQueue.horizontalHeaderItem(4)
        item.setText(_translate("Form", "设定温度"))
        item = self.tbTempQueue.horizontalHeaderItem(5)
        item.setText(_translate("Form", "风速"))
        item = self.tbTempQueue.horizontalHeaderItem(6)
        item.setText(_translate("Form", "耗能"))
        item = self.tbTempQueue.horizontalHeaderItem(7)
        item.setText(_translate("Form", "当前计费"))

