# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Reporter.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1100, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btSettle = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btSettle.setFont(font)
        self.btSettle.setObjectName("btSettle")
        self.horizontalLayout_5.addWidget(self.btSettle)
        self.dateEdit = QtWidgets.QDateEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dateEdit.setFont(font)
        self.dateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(7999, 12, 31), QtCore.QTime(23, 59, 59)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_5.addWidget(self.dateEdit)
        self.btRefresh = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btRefresh.setFont(font)
        self.btRefresh.setObjectName("btRefresh")
        self.horizontalLayout_5.addWidget(self.btRefresh)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabDatail = QtWidgets.QWidget()
        self.tabDatail.setObjectName("tabDatail")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabDatail)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tbDetail = QtWidgets.QTableWidget(self.tabDatail)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbDetail.setFont(font)
        self.tbDetail.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tbDetail.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbDetail.setObjectName("tbDetail")
        self.tbDetail.setColumnCount(11)
        self.tbDetail.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbDetail.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbDetail.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbDetail.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbDetail.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbDetail.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbDetail.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbDetail.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbDetail.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbDetail.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbDetail.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbDetail.setHorizontalHeaderItem(10, item)
        self.verticalLayout_2.addWidget(self.tbDetail)
        self.tabWidget.addTab(self.tabDatail, "")
        self.tabBillList = QtWidgets.QWidget()
        self.tabBillList.setObjectName("tabBillList")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabBillList)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tbBillList = QtWidgets.QTableWidget(self.tabBillList)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbBillList.setFont(font)
        self.tbBillList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tbBillList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbBillList.setObjectName("tbBillList")
        self.tbBillList.setColumnCount(7)
        self.tbBillList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbBillList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbBillList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbBillList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbBillList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbBillList.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbBillList.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbBillList.setHorizontalHeaderItem(6, item)
        self.verticalLayout_4.addWidget(self.tbBillList)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.tabBillList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.label_totalIncome = QtWidgets.QLabel(self.tabBillList)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_totalIncome.setFont(font)
        self.label_totalIncome.setText("")
        self.label_totalIncome.setObjectName("label_totalIncome")
        self.horizontalLayout_6.addWidget(self.label_totalIncome)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.tabWidget.addTab(self.tabBillList, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "报表"))
        self.btSettle.setText(_translate("Form", "结帐"))
        self.btRefresh.setText(_translate("Form", "刷新"))
        self.tbDetail.setSortingEnabled(True)
        item = self.tbDetail.horizontalHeaderItem(0)
        item.setText(_translate("Form", "房间号"))
        item = self.tbDetail.horizontalHeaderItem(1)
        item.setText(_translate("Form", "用户等级"))
        item = self.tbDetail.horizontalHeaderItem(2)
        item.setText(_translate("Form", "开机时间"))
        item = self.tbDetail.horizontalHeaderItem(3)
        item.setText(_translate("Form", "关机时间"))
        item = self.tbDetail.horizontalHeaderItem(4)
        item.setText(_translate("Form", "时长"))
        item = self.tbDetail.horizontalHeaderItem(5)
        item.setText(_translate("Form", "调温次数"))
        item = self.tbDetail.horizontalHeaderItem(6)
        item.setText(_translate("Form", "回温次数"))
        item = self.tbDetail.horizontalHeaderItem(7)
        item.setText(_translate("Form", "调风次数"))
        item = self.tbDetail.horizontalHeaderItem(8)
        item.setText(_translate("Form", "耗能（kW·h）"))
        item = self.tbDetail.horizontalHeaderItem(9)
        item.setText(_translate("Form", "费用（元）"))
        item = self.tbDetail.horizontalHeaderItem(10)
        item.setText(_translate("Form", "单号"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDatail), _translate("Form", "详单"))
        self.tbBillList.setSortingEnabled(True)
        item = self.tbBillList.horizontalHeaderItem(0)
        item.setText(_translate("Form", "日期"))
        item = self.tbBillList.horizontalHeaderItem(1)
        item.setText(_translate("Form", "单号"))
        item = self.tbBillList.horizontalHeaderItem(2)
        item.setText(_translate("Form", "房间号"))
        item = self.tbBillList.horizontalHeaderItem(3)
        item.setText(_translate("Form", "用户级别"))
        item = self.tbBillList.horizontalHeaderItem(4)
        item.setText(_translate("Form", "总消费（元）"))
        item = self.tbBillList.horizontalHeaderItem(5)
        item.setText(_translate("Form", "折扣率"))
        item = self.tbBillList.horizontalHeaderItem(6)
        item.setText(_translate("Form", "应收金额（元）"))
        self.label.setText(_translate("Form", "总收入（元）："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBillList), _translate("Form", "账单"))

