# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_SubMachine.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(622, 459)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btClose = QtWidgets.QPushButton(Form)
        self.btClose.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btClose.setFont(font)
        self.btClose.setObjectName("btClose")
        self.horizontalLayout_12.addWidget(self.btClose)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lcd_setTemp = QtWidgets.QLCDNumber(Form)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.lcd_setTemp.setFont(font)
        self.lcd_setTemp.setFrameShape(QtWidgets.QFrame.Box)
        self.lcd_setTemp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_setTemp.setLineWidth(1)
        self.lcd_setTemp.setMidLineWidth(0)
        self.lcd_setTemp.setSmallDecimalPoint(False)
        self.lcd_setTemp.setDigitCount(2)
        self.lcd_setTemp.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd_setTemp.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcd_setTemp.setProperty("value", 25.0)
        self.lcd_setTemp.setProperty("intValue", 25)
        self.lcd_setTemp.setObjectName("lcd_setTemp")
        self.gridLayout.addWidget(self.lcd_setTemp, 0, 1, 6, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.label_mode = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_mode.setFont(font)
        self.label_mode.setObjectName("label_mode")
        self.gridLayout.addWidget(self.label_mode, 5, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 0, 0, 3, 1)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 2, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(43, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.leRoomId = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.leRoomId.setFont(font)
        self.leRoomId.setObjectName("leRoomId")
        self.horizontalLayout_3.addWidget(self.leRoomId)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.cb_userLevel = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cb_userLevel.setFont(font)
        self.cb_userLevel.setObjectName("cb_userLevel")
        self.cb_userLevel.addItem("")
        self.cb_userLevel.addItem("")
        self.horizontalLayout_3.addWidget(self.cb_userLevel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_windSpeed = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_windSpeed.setFont(font)
        self.label_windSpeed.setObjectName("label_windSpeed")
        self.horizontalLayout.addWidget(self.label_windSpeed)
        self.horizontalLayout_9.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_roomTemp = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_roomTemp.setFont(font)
        self.label_roomTemp.setObjectName("label_roomTemp")
        self.horizontalLayout_2.addWidget(self.label_roomTemp)
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.label_energy = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_energy.setFont(font)
        self.label_energy.setObjectName("label_energy")
        self.horizontalLayout_7.addWidget(self.label_energy)
        self.label_16 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_7)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.label_money = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_money.setFont(font)
        self.label_money.setObjectName("label_money")
        self.horizontalLayout_4.addWidget(self.label_money)
        self.label_13 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_4)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btWindSpeedDown = QtWidgets.QPushButton(Form)
        self.btWindSpeedDown.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.btWindSpeedDown.setFont(font)
        self.btWindSpeedDown.setObjectName("btWindSpeedDown")
        self.horizontalLayout_5.addWidget(self.btWindSpeedDown)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.btWindSpeedUp = QtWidgets.QPushButton(Form)
        self.btWindSpeedUp.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.btWindSpeedUp.setFont(font)
        self.btWindSpeedUp.setObjectName("btWindSpeedUp")
        self.horizontalLayout_5.addWidget(self.btWindSpeedUp)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_5)
        spacerItem10 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btSetTempDown = QtWidgets.QPushButton(Form)
        self.btSetTempDown.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.btSetTempDown.setFont(font)
        self.btSetTempDown.setObjectName("btSetTempDown")
        self.horizontalLayout_6.addWidget(self.btSetTempDown)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.btSetTempUp = QtWidgets.QPushButton(Form)
        self.btSetTempUp.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.btSetTempUp.setFont(font)
        self.btSetTempUp.setCheckable(False)
        self.btSetTempUp.setChecked(False)
        self.btSetTempUp.setAutoDefault(False)
        self.btSetTempUp.setDefault(False)
        self.btSetTempUp.setFlat(False)
        self.btSetTempUp.setObjectName("btSetTempUp")
        self.horizontalLayout_6.addWidget(self.btSetTempUp)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_6)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_11)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "从控机"))
        self.btClose.setText(_translate("Form", "开机"))
        self.label.setText(_translate("Form", "℃"))
        self.label_mode.setText(_translate("Form", "--"))
        self.label_9.setText(_translate("Form", "房间号："))
        self.cb_userLevel.setItemText(0, _translate("Form", "普通用户"))
        self.cb_userLevel.setItemText(1, _translate("Form", "VIP"))
        self.label_7.setText(_translate("Form", "风速："))
        self.label_windSpeed.setText(_translate("Form", "--"))
        self.label_4.setText(_translate("Form", "房间温度："))
        self.label_roomTemp.setText(_translate("Form", "--"))
        self.label_6.setText(_translate("Form", "℃"))
        self.label_14.setText(_translate("Form", "耗能："))
        self.label_energy.setText(_translate("Form", "0"))
        self.label_16.setText(_translate("Form", "kW·h"))
        self.label_11.setText(_translate("Form", "当前计费："))
        self.label_money.setText(_translate("Form", "0"))
        self.label_13.setText(_translate("Form", "元 "))
        self.btWindSpeedDown.setText(_translate("Form", "-"))
        self.label_2.setText(_translate("Form", "风速"))
        self.btWindSpeedUp.setText(_translate("Form", "+"))
        self.btSetTempDown.setText(_translate("Form", "-"))
        self.label_3.setText(_translate("Form", "温度"))
        self.btSetTempUp.setText(_translate("Form", "+"))

